FROM debian:buster-slim

LABEL original_maintainer "Signal Flag Z"
LABEL edited_by "tk44fk40"

# RUN echo "enable deb-src..."

# RUN echo "change apt repo to mirror..."
# # http://ftp.jp.debian.org/debian/


# RUN echo "updating apt repo..." \
#   && apt-get update \
#   && apt-get upgrade -y

# RUN echo "install libs as tools..." \
#   && apt-get -y install\
#    sudo \
#    autoconf \
#    automake \
#    build-essential \
#    cmake \
#    git-core \
#    libass-dev \
#    libfreetype6-dev \
#    libsdl2-dev \
#    libtool \
#    libva-dev \
#    libvdpau-dev \
#    libvorbis-dev \
#    libxcb1-dev \
#    libxcb-shm0-dev \
#    libxcb-xfixes0-dev \
#    pkg-config \
#    texinfo \
#    wget \
#    zlib1g-dev \
#   && apt-get -y install\
#    nasm \
#    yasm \
#    sudo\
#   && apt-get -y install\
#    libx264-dev \
#    libvpx-dev \
#   && apt-get -y autoremove \
#   && apt-get -y clean \
#   && rm -rf /var/lib/apt/lists/* \
#   && echo "Done."

# COPY ./buildFF.sh  /root

# ALSA Version
ENV V_ALSA="1.2.7.2"

#CMD ["/bin/bash", "-c",  "/home/buildFF.sh"]
